export const breadcrumbItemsMap = new Map<string, string>([
  ['contingent', 'Контингент'],
  ['', 'Главная'],
  ['addstudent', 'Добавление студента'],
  ['contingentselection', 'Массовые операции'],
  ['contingentsettings', 'Настройки отображения'],
  ["studentcardsettings", "Настройки карточки студента"],
  ['contingentjournal', ''],
  ['academicstate', 'Академические статусы'],
  ['militarydoctypes', 'Документы воинского учета'],
  ['militaryranks', 'Воинские звания'],
  ['militarystatuses', 'Категории воинского учёта'],
  ['militarystockcategories', 'Категории воинских запасов'],
  ['militarycommissariat', 'Военные комиссариаты'],
  ['budget', 'Источники финансирования'],
  ["budgetcategory", "Категории финансирования"],
  ["budgetsubcategory","Подкатегория финансирования"],
  ['identificationtype', 'Документы, удостоверяющие личность'],
  ['languages', 'Изучаемые иностранные языки'],
  ['phonetypes', 'Типы телефонов'],
  ['educationdoctypes', 'Типы документов об образовании'],
  ['citizenship', 'Гражданство'],
  ['targetedtraining', 'Целевое обучение'],
  ['citizenshiptype', 'Типы гражданства'],
  ['familymemberstatuses', 'Статусы членов семьи'],
  ['dictmaritalstatus', 'Семейное положение'],
  ['emailtypes', 'Типы email'],
  ['streettypes', 'Типы улиц'],
  ['documentnames', 'Наименования документов'],
  ['institutiontype', 'Типы учебных заведений'],
  ['health', 'Группы здоровья'],
  ['sportcategory', 'Спортивные разряды'],
  ['sporttype', 'Виды спорта'],
  ['spravkatype', 'Тип справки'],
  ['benefits', 'Льготы'],
  ['citytypes', 'Виды населенных пунктов'],
  ['ordertypes', 'Категории приказов'],
  ['additionalfields', 'Дополнительные поля'],
  ['languagelevels', 'Уровни владения языком'],
  ['filial', 'Филиалы'],
  ['organization', 'Сторонние организации'],
  ['orderscategory', 'Подкатегории приказов'],
  ['progress', 'Успеваемость'],
  ['achievements', 'Достижения'],
  ['orders', 'Приказы'],
  ['personaldata', 'Персональные данные'],
  ['certificate', 'Справки'],
  ['military', 'Воинский учет'],
  ["militarycertificates", "Справки по воинскому учету"],
  ['academicgroupshome', 'Академические группы'],
  ['addacademicgroups', 'Создание академической группы'],
  ['editacademicgroups', 'Редактирование академической группы'],
  ['middlecontrol', 'Промежуточный контроль'],
  ['currentcontrol', 'Текущий контроль'],
  ['contingentjournal', 'Журнал'],
  ['studplan', 'Смена учебного плана'],
  ['documents', 'Документы'],
  ['history', 'История изменений'],
  ['dictachievement', 'Категории достижений'],
  ['dictmarkcriterialevel', 'Справочник уровня критериев оценок'],
  ['dictcontrolaction', 'Контрольные акции'],
  ['codearticle', 'Статьи ТК РФ для справки-вызов'],
  ['dictmarkchangereason', 'Причина смены оценки'],
  ['dicterrordescription', 'Ошибки при перезачете дисциплин'],
  ['militarycategories', 'Категории годности к военной службе'],
  ['achievementsstatuses', 'Статусы достижений'],
  ['militaryformtypes', 'Типы справок по воинскому учёту'],
  ['militaryprofiles', 'Составы (профили)'],
  ['militarystates', 'Состояния воинского учета'],
  ['nonemploymentreasons', 'Причины нетрудоустройства'],
  ['dictgeneralsheet', 'Общая ведомость по дисциплине'],
  ['worktypes', 'Типы работ'],
  ['localsignatoryrole', 'Роли локальных подписантов'],
  ['constructor-edu-group-name', 'Конструктор названий групп'],

  ['dicts', 'Справочники'],
  ['traininglevel', 'Уровень подготовки'],
  ['studylevel', 'Уровень образования'],
  ['studyformtype', 'Тип формы обучения'],
  ['studyform', 'Форма обучения'],
  ['qualificationdegree', 'Квалификации'],
  ['studytechnology', 'Технология обучения'],
  ['controlaction', 'Контрольные акции'],
  ['mark', 'Оценки'],
  ['discipline', 'Дисциплина'],
  ['disciplinetype', 'Тип дисциплины'],
  ['dictcertificatepurpose', 'Места для предоставления справки'],
  ['studentcards', 'Карты'],

  ['education', 'Образование'],
  ['plans', 'Учебные планы'],
  ['add-plan', 'Добавление плана'],
  ['copy-plan', 'Копирование учебного плана'],
  ['add-discipline', 'Добавление дисциплины'],
  ['edit-discipline', 'Редактирование дисциплины'],
  ['reattach-plan', 'Перезакрепление за другой ОП'],
  ['global-schedule-settings', 'Настройка графика учебного процесса'],
  ['export-shedule', 'Экспорт графиков учебного процесса'],
  ['dictdisciplinetype', 'Тип дисциплины'],
  ['department', 'Кафедры'],

  ['profile', 'Личный кабинет сотрудника'],
  ['useraccess', 'Настройки доступа'],

  ['standard', 'Образовательные стандарты'],
  ['oop', 'Образовательные программы'],
  ['matrixcompetence', 'Матрица компетенций'],
  ['competence', 'Компетенции'],
  ['dictcomponent', 'Компонент'],
  ['dictcomponenttype', 'Тип компонента'],
  ['standard', 'Образовательные стандарты'],
  ['dictotherdocumenttypes', 'Типы прочих документов'],
  ['dictfaculty', 'Факультеты'],
  ['complaintmanagementstatus', 'Статусы управления жалобами'],
  ['paymentstate', 'Статусы состояния платежа'],
  ['employmentstatus', 'Статусы занятости работников'],
  ['dictcycle', 'Циклы'],
  ['dictcycletype', 'Тип цикла'],
  ['dicttraininglevels', 'Уровни подготовки'],
  ['sciencebranch', 'Отрасль науки'],
  ['dictTypeWorkDisciplineAdditional', 'Дополнительные работы по дисциплине'],
  ['standardtype', 'Тип стандарта'],
  ['dictWorkCategorySchedule', 'Категории работ графика'],
  ['dictWorkScheduleStudyProcessType', 'Виды работ графика учебного процесса'],
  ['dictIndustrialPartner', 'Индустриальный партнер'],
  ['dictgroupstandardlimitation', 'Группы ограничений стандарта'],
  ['dictstandardlimitationsetting', 'Ограничения стандарта'],
  ['dictWorkStudyPlanType', 'Виды работ учебного плана'],
  ['dictLessonType', 'Тип проведения занятий'],
  ['dictLessonForm', 'Форма проведения занятий'],
  ['dictAcceleratedStudyBase', 'База ускоренного обучения'],
  ['dictstandardlimitation', 'Ограничения стандарта'],
  ['dictEnlargedGroupSpecialization', 'Укрупненные группы специальностей'],
  ['dictplanstatus', 'Статус плана'],

  ['switchuser', 'Просмотр от другого лица'],

  //#region Signatory
  ['signatory', 'Настройки списка подписантов'],
  ['signatoryrole', 'Категория подписантов'],
  //#endregion

  //['alert', 'Объявления и новости'],
  //['author', 'Объявления и новости'],
  ['modify', 'Создать новое оповещение'],
  //['show', 'Объявления и новости'],
  ['announcement', 'Создать новое оповещение'],
  ['announcements', 'Объявления и новости'],

  ['disciplineworkload', 'Нагрузка'],
  ['dictTeachers', "Преподаватели"],
  ['dictTeachers', 'Преподаватели'],
  ['dictadditionalwork', 'Дополнительные работы'],
  ['dicttypeaddwork', 'Типы дополнительных работ'],
  ['dictcalculationcathedralwork', 'Доступные кафедральные работы для способа расчета'],
  ['dictexamtype', 'Виды экзаменов кафедральных работ'],
  ['increasedcoefficient', 'Повышенные коэффициенты'],
  ['practicetype', 'Виды практик в настройках конструктора поручений'],

  ['classroom', 'Аудиторный фонд'],
  ['building', 'Корпуса'],
  ['auditorium', 'Типы аудиторий '],
  ['assign', 'Назначения аудиторий'],
  ['access', 'Настройки доступа'],
  ['parameters', 'Аудитория'],

  ['export-schedule', 'Экспорт графиков учебного процесса'],
  ['register', 'Реестр учебных планов'],
  ['registerdevelopers', 'Ответственные за разработку'],

  ['technicaladministrators', 'Технические администраторы'],
  ['cadrebase', 'Кадровая база'],
  ['paramperson', 'Сведения о сотруднике'],
  ['personcard', 'Карточка сотрудника'],
  ['posts', 'Должности'],
  ['sciencedegree', 'Ученые степени'],
  ['departments', 'Подразделения'],
  ['departmentsname', 'Названия подразделений'],
  ['departmentstype', 'Типы подразделений'],

  ['publications', 'Публикации'],
  ['authors', 'Авторы'],
  ['authorCard', 'Автор'],
  ['addAuthor', 'Добавление автора'],
  ['addAuthorForPublication', 'Добавление автора'],
  ['summaryInfo', 'Сводная информация'],
  ['reports', 'Отчеты'],
  ['newPublication', 'Новая публикация'],
  ['newPublication/', 'Публикация'],
  ['dictPosts', 'Должности'],
  ['dictQuartiles', 'Квартили'],
  ['dictScienceDegrees', 'Ученые степени'],
  ['dictPublicationTypes', 'Типы публикаций'],
  ['dictPublicationSubTypes', 'Виды публикаций'],
  ['dictScientometricBases', 'Индексация'],
  ['dictCodes', 'Коды'],
  ['dictAuthorRoles', 'Роли автора'],
  ['dictOrganizations', 'Организации'],
  ['userAccess', 'Настройки доступа'],

  ['payslip', "Расчетные листы"],

  ['transferdisciplines', 'Перезачет дисциплин'],
  ['cards', 'Карты'],
  ['reestr', 'Реестр'],
  ['addtolistforming', 'Добавление студента'],
  ['salaryproject', 'Зарплатные проекты'],
  ['test', 'Тестовый справочник'],
]);
