version: '3.8'

services:
  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    container_name: notification_service
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
     - "notifications_db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=notifications;Username=postgres;Password=postgres
    networks:
      - notification_network

  notifications_db:
    image: postgres:latest
    container_name: notifications_db
    environment:
      - POSTGRES_DB=notifications
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/notifications-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - notification_network

networks:
  notification_network:
    driver: bridge