version: '3.9'


services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=notifications;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - dockerapi


  db:
    image: postgres:latest  
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - dockerapi


  lk-person:
    container_name: lk-person
    build:
      context: ../../App/
      dockerfile: /Dockerfile
    ports:
      - "8451:80"
    networks:
      - dockerapi

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672" # Management plugin port
      - "5672:5672"   # RabbitMQ port
    networks:
      - dockerapi

networks:
  dockerapi:
    driver: bridge

